import eslintJs from '@eslint/js';
import { defineConfig } from 'eslint/config';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import globals from 'globals';
import typescriptEslint from 'typescript-eslint';

import relativeExtensions from './custom-rules/relative-extensions.js';

export default defineConfig([
  {
    name: 'rcx-dev/ignores',
    ignores: ['**/dist/**/*', '**/build/**/*', '**/coverage/**/*'],
  },
  eslintJs.configs.recommended,
  typescriptEslint.configs.recommended,
  {
    name: 'rcx-dev/setup',
    languageOptions: {
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  {
    name: 'rcx-dev/base',
    rules: {
      strict: ['error', 'global'],
      eqeqeq: 'error',
      'no-duplicate-imports': ['error', { includeExports: true }],
      'block-scoped-var': 'error',
      'no-constant-condition': 'error',
      'no-console': 'error',
      'no-debugger': 'error',
      'no-lonely-if': 'error',
      'no-lone-blocks': 'error',
      'no-nested-ternary': 'error',
      'no-dupe-keys': 'error',
      'no-extra-boolean-cast': 'error',
      'no-irregular-whitespace': 'error',
      'no-else-return': 'error',
      'no-eval': 'error',
      'no-multi-str': 'error',
      'no-self-compare': 'error',
      'no-useless-call': 'error',
      'no-shadow-restricted-names': 'error',
      'no-shadow': 'off',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-unreachable': 'error',
      'no-unused-vars': ['error', { varsIgnorePattern: '^_\\w' }],
      'no-use-before-define': 'error',

      radix: 'error',
      curly: 'error',
      'no-fallthrough': 'error',
      'default-case': 'error',

      'no-var': 'error',
      'no-unused-expressions': 'error',
      camelcase: [
        'error',
        {
          properties: 'always',
          allow: ['^UNSAFE_', 'call_id'],
        },
      ],
      'no-restricted-globals': [
        'error',
        'error',
        'window',
        'URL',
        'history',
        'dispatchEvent',
        'require',
        'postMessage',
        'blur',
        'focus',
        'close',
        'frames',
        'self',
        'parent',
        'opener',
        'top',
        'length',
        'closed',
        'location',
        'origin',
        'name',
        'locationbar',
        'menubar',
        'personalbar',
        'scrollbars',
        'statusbar',
        'toolbar',
        'status',
        'frameElement',
        'navigator',
        'customElements',
        'external',
        'screen',
        'innerWidth',
        'innerHeight',
        'scrollX',
        'pageXOffset',
        'scrollY',
        'pageYOffset',
        'screenX',
        'screenY',
        'outerWidth',
        'outerHeight',
        'devicePixelRatio',
        'clientInformation',
        'screenLeft',
        'screenTop',
        'defaultStatus',
        'defaultstatus',
        'styleMedia',
        'onanimationend',
        'onanimationiteration',
        'onanimationstart',
        'onsearch',
        'ontransitionend',
        'onwebkitanimationend',
        'onwebkitanimationiteration',
        'onwebkitanimationstart',
        'onwebkittransitionend',
        'isSecureContext',
        'onabort',
        'onblur',
        'oncancel',
        'oncanplay',
        'oncanplaythrough',
        'onchange',
        'onclick',
        'onclose',
        'oncontextmenu',
        'oncuechange',
        'ondblclick',
        'ondrag',
        'ondragend',
        'ondragenter',
        'ondragleave',
        'ondragover',
        'ondragstart',
        'ondrop',
        'ondurationchange',
        'onemptied',
        'onended',
        'onerror',
        'onfocus',
        'oninput',
        'oninvalid',
        'onkeydown',
        'onkeypress',
        'onkeyup',
        'onload',
        'onloadeddata',
        'onloadedmetadata',
        'onloadstart',
        'onmousedown',
        'onmouseenter',
        'onmouseleave',
        'onmousemove',
        'onmouseout',
        'onmouseover',
        'onmouseup',
        'onmousewheel',
        'onpause',
        'onplay',
        'onplaying',
        'onprogress',
        'onratechange',
        'onreset',
        'onresize',
        'onscroll',
        'onseeked',
        'onseeking',
        'onselect',
        'onstalled',
        'onsubmit',
        'onsuspend',
        'ontimeupdate',
        'ontoggle',
        'onvolumechange',
        'onwaiting',
        'onwheel',
        'onauxclick',
        'ongotpointercapture',
        'onlostpointercapture',
        'onpointerdown',
        'onpointermove',
        'onpointerup',
        'onpointercancel',
        'onpointerover',
        'onpointerout',
        'onpointerenter',
        'onpointerleave',
        'onafterprint',
        'onbeforeprint',
        'onbeforeunload',
        'onhashchange',
        'onlanguagechange',
        'onmessage',
        'onmessageerror',
        'onoffline',
        'ononline',
        'onpagehide',
        'onpageshow',
        'onpopstate',
        'onrejectionhandled',
        'onstorage',
        'onunhandledrejection',
        'onunload',
        'performance',
        'stop',
        'open',
        'print',
        'captureEvents',
        'releaseEvents',
        'getComputedStyle',
        'matchMedia',
        'moveTo',
        'moveBy',
        'resizeTo',
        'resizeBy',
        'getSelection',
        'find',
        'createImageBitmap',
        'scroll',
        'scrollTo',
        'scrollBy',
        'onappinstalled',
        'onbeforeinstallprompt',
        'crypto',
        'ondevicemotion',
        'ondeviceorientation',
        'ondeviceorientationabsolute',
        'indexedDB',
        'webkitStorageInfo',
        'chrome',
        'visualViewport',
        'speechSynthesis',
        'webkitRequestFileSystem',
        'webkitResolveLocalFileSystemURL',
        'openDatabase',
        'setTimeout',
        'clearTimeout',
        'setInterval',
        'clearInterval',
        'requestAnimationFrame',
        'cancelAnimationFrame',
        'addEventListener',
        'removeEventListener',
      ],
    },
  },
  {
    name: 'rcx-dev/imports',
    plugins: {
      'simple-import-sort': simpleImportSort,
    },
    rules: {
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
    },
  },
  {
    name: 'rcx-dev/typescript',
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'no-undef': 'off',
      'no-unused-vars': 'off',
      'no-use-before-define': 'off',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/member-delimiter-style': 'off',
      '@typescript-eslint/type-annotation-spacing': 'off',
      '@typescript-eslint/no-unused-vars': 'error',
      '@typescript-eslint/no-use-before-define': 'error',
      '@typescript-eslint/no-shadow': 'error',
    },
  },
  {
    name: 'rcx-dev/custom-rules',
    plugins: {
      custom: {
        rules: {
          'relative-extensions': relativeExtensions,
        },
      },
    },
    rules: {
      'custom/relative-extensions': 'error',
    },
  },
  eslintPluginPrettierRecommended,
]);
